# Licensed to the Apache Software Foundation (ASF) - Maven Wrapper configuration.
# Pins the Maven distribution and the wrapper jar this checkout uses.
wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
